-- MySQL Script generated by MySQL Workbench
-- seg 22 ago 2022 21:32:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ob_material_didatico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ob_material_didatico` (
  `id_material_didatico` INT NOT NULL AUTO_INCREMENT,
  `id_professor` INT NOT NULL,
  `titulo` VARCHAR(450) NOT NULL,
  `descricao` VARCHAR(45000) NOT NULL,
  `arquivo` VARCHAR(450) NOT NULL,
  `link_drive` VARCHAR(450) NOT NULL,
  `fl_aprovado` TINYINT(1) NOT NULL default 0,
  PRIMARY KEY (`id_material_didatico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ob_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ob_video` (
  `id_video` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(450) NOT NULL,
  `descricao` VARCHAR(45000) NOT NULL,
  `arquivo` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`id_video`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ob_relato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ob_relato` (
  `id_relato` INT NOT NULL AUTO_INCREMENT,
  `arquivo` VARCHAR(450) NULL,
  `descricao` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`id_relato`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
